web:
    build: .
    container_name: instantwp
    environment:
        - INSTANTWP_URL
        - INSTANTWP_PLUGINS
        - INSTANTWP_LOCALE
    ports:
        - "80:80"
    volumes:
        - ./public/:/var/www/html/
        - ./mysql-data/:/var/lib/mysql/